# Auth section
[auth]
api_id = 12345
api_hash = "your_api_hash"
phone_number = "+1234567890"

# Define schedules - at least "default" schedule is required
[[schedules]]
name = "default"          # Required: must have a schedule named "default"
start_of_day = "10:00:00"
end_of_day = "19:00:00"   # End of working day - script won't mute during work hours
timezone = "auto"         # Use "auto" for system timezone, or specify like "Europe/London", "America/New_York", etc.
weekends = ["Sat", "Sun"]

# Working weekends (specific dates or date intervals)
working_weekends = [
    "2025-11-01",
    ["2025-12-25", "2025-12-31"]  # Date interval
]

# Nonworking weekdays (specific dates or date intervals)  
nonworking_weekdays = [
    "2025-12-31", 
    ["2026-01-01", "2026-01-07"]  # Date interval
]

# Example of additional schedules with inheritance
# [[schedules]]
# name = "work"
# parent = "default"        # Inherits from default, can override any properties
# start_of_day = "09:00:00" # Override: work starts earlier
# timezone = "UTC"          # Override: use UTC timezone

# [[schedules]]
# name = "duty"
# parent = "work"           # Inherits from work schedule
# weekends = []             # Override: no weekends (24/7 duty)
# working_weekends = []     # Clear parent's working weekends

# Group-specific settings (optional, works with both legacy and multi-schedule)
# [[group_settings]]
# name = "Work Team Chat"
# schedule = "work"         # Use the "work" schedule for this exact group name

# [[group_settings]]
# name_pattern = "duty.*"   # Regex pattern to match group names starting with "duty"
# schedule = "duty"         # Use the "duty" schedule for matching groups

# [[group_settings]]
# name_pattern = "weekend.*"
# schedule = "default"      # Use default schedule for weekend groups
